name: CI
on:
  pull_request:
  push:
    branches: [main]
permissions:
  actions: read
  contents: read
  security-events: write
  pull-requests: write
  issues: write
jobs:
  ci:
    uses: aurea-io/aurea-ci/.github/workflows/ci.yml@main
    with:
      project-type: node-frontend
